// SYNTHETIC development hands only. These are invented patterns in NMJL *style*
// (categories, group shapes, joker rules) and deliberately do NOT reproduce any
// hand from any year's NMJL card. Real hands enter the system exclusively via
// the user parsing their own physical card (BYOC).
import {
  HandTemplate,
  dragon,
  flower,
  kong,
  num,
  one,
  pair,
  pung,
  quint,
  seq,
  soap,
  wind,
} from "./hands.js";

export const SAMPLE_HANDS: HandTemplate[] = [
  {
    id: "sample-evens-1",
    name: "FF 2222 4444 66 88",
    category: "Evens (sample)",
    points: 25,
    concealed: false,
    groups: [
      pair(flower),
      kong(num(2, "A")),
      kong(num(4, "A")),
      pair(num(6, "B")),
      pair(num(8, "B")),
    ],
  },
  {
    id: "sample-run-1",
    name: "111 2222 333 4444 (run, 2 suits)",
    category: "Consecutive Run (sample)",
    points: 25,
    concealed: false,
    groups: [
      pung(seq(0, "A")),
      kong(seq(1, "A")),
      pung(seq(2, "B")),
      kong(seq(3, "B")),
    ],
  },
  {
    id: "sample-odds-1",
    name: "111 333 555 777 99",
    category: "Odds (sample)",
    points: 30,
    concealed: false,
    groups: [
      pung(num(1, "A")),
      pung(num(3, "A")),
      pung(num(5, "A")),
      pung(num(7, "B")),
      pair(num(9, "B")),
    ],
  },
  {
    id: "sample-winds-1",
    name: "NNNN EEE WWW SSSS",
    category: "Winds (sample)",
    points: 30,
    concealed: false,
    groups: [
      kong(wind("N")),
      pung(wind("E")),
      pung(wind("W")),
      kong(wind("S")),
    ],
  },
  {
    id: "sample-quints-1",
    name: "11111 22222 NNNN",
    category: "Quints (sample)",
    points: 40,
    concealed: false,
    groups: [quint(num(1, "A")), quint(num(2, "B")), kong(wind("N"))],
  },
  {
    id: "sample-dragons-1",
    name: "FF 111 DDDD 99 DDD (matching dragons)",
    category: "Dragons (sample)",
    points: 30,
    concealed: false,
    groups: [
      pair(flower),
      pung(num(1, "A")),
      kong(dragon("A")),
      pair(num(9, "B")),
      pung(dragon("B")),
    ],
  },
  {
    id: "sample-year-1",
    name: "FFFF 2027 222 222",
    category: "Year (sample)",
    points: 25,
    concealed: false,
    groups: [
      kong(flower),
      one(num(2, "A")),
      one(soap),
      one(num(2, "A")),
      one(num(7, "A")),
      pung(num(2, "B")),
      pung(num(2, "C")),
    ],
  },
  {
    id: "sample-pairs-1",
    name: "FF 11 33 55 77 99 NN (concealed)",
    category: "Singles & Pairs (sample)",
    points: 50,
    concealed: true,
    groups: [
      pair(flower),
      pair(num(1, "A")),
      pair(num(3, "A")),
      pair(num(5, "A")),
      pair(num(7, "B")),
      pair(num(9, "B")),
      pair(wind("N")),
    ],
  },
];
